#pragma once

#ifdef USE_COLOR
#define ANSI_COLOR(__wstring__)	L"\033[" __wstring__
#else
#define ANSI_COLOR(__wstring__)	L""
#endif

#define ANSI_BOLD	ANSI_COLOR(L"1m")
#define ANSI_REV	ANSI_COLOR(L"0;7m")
#define ANSI_CLR	ANSI_COLOR(L"0m")

#define ANSI_BLACK	ANSI_COLOR(L"30m")
#define ANSI_RED	ANSI_COLOR(L"31m")
#define ANSI_GREEN	ANSI_COLOR(L"32m")
#define ANSI_YELLOW	ANSI_COLOR(L"33m")
#define ANSI_BLUE	ANSI_COLOR(L"34m")
#define ANSI_MAGENTA	ANSI_COLOR(L"35m")
#define ANSI_CYAN	ANSI_COLOR(L"36m")
#define ANSI_WHITE	ANSI_COLOR(L"37m")

#define ANSI_LOBLACK	ANSI_COLOR(L"0;30m")
#define ANSI_LORED	ANSI_COLOR(L"0;31m")
#define ANSI_LOGREEN	ANSI_COLOR(L"0;32m")
#define ANSI_LOYELLOW	ANSI_COLOR(L"0;33m")
#define ANSI_LOBLUE	ANSI_COLOR(L"0;34m")
#define ANSI_LOMAGENTA	ANSI_COLOR(L"0;35m")
#define ANSI_LOCYAN	ANSI_COLOR(L"0;36m")
#define ANSI_LOWHITE	ANSI_COLOR(L"0;37m")

#define ANSI_HIBLACK	ANSI_COLOR(L"1;30m")
#define ANSI_HIRED	ANSI_COLOR(L"1;31m")
#define ANSI_HIGREEN	ANSI_COLOR(L"1;32m")
#define ANSI_HIYELLOW	ANSI_COLOR(L"1;33m")
#define ANSI_HIBLUE	ANSI_COLOR(L"1;34m")
#define ANSI_HIMAGENTA	ANSI_COLOR(L"1;35m")
#define ANSI_HICYAN	ANSI_COLOR(L"1;36m")
#define ANSI_HIWHITE	ANSI_COLOR(L"1;37m")
